import hashlib

class Transaction:
    def __init__(self, sender_pubkey, receiver_pubkey, amount, signature):
        self.sender = sender_pubkey
        self.receiver = receiver_pubkey
        self.amount = amount
        self.signature = signature
        self.txid = None  # Will be generated by quantum_hash

def create_transaction(sender, receiver, amount, signature):
    # Input validation
    if not sender or not isinstance(sender, str):
        raise ValueError("Sender must be a non-empty string")
    if not receiver or not isinstance(receiver, str):
        raise ValueError("Receiver must be a non-empty string")
    if not isinstance(amount, (int, float)) or amount <= 0:
        raise ValueError("Transaction amount must be a positive number")
    if not signature or not isinstance(signature, str):
        raise ValueError("Transaction must have a valid signature string")
        
    return {
        'sender': sender,
        'receiver': receiver,
        'amount': amount,
        'signature': signature
    }

def serialize(transaction):
    return f"{transaction['sender']}{transaction['receiver']}{transaction['amount']}{transaction['signature']}"
