services:
  quantum_currency:
    build:
      context: ../../../
      dockerfile: completion/deployment/docker/Dockerfile
    container_name: quantum_currency_app
    env_file:
      - ../../../config/.env
    ports:
      - "8333:8333"
    volumes:
      - ../../../src:/app/src
      - ../../../config:/app/config
    restart: unless-stopped
